### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fellu** [divio/aldryn-search#33]
```
from aldryn_search.views import AldrynSearchView
```

  File "/home/fellu/code/own/asm_cms/env/lib/python3.3/site-packages/aldryn_search/views.py", line 9, in <module>
    from aldryn_common.paginator import DiggPaginator
  File "/home/fellu/code/own/asm_cms/env/lib/python3.3/site-packages/aldryn_common/paginator.py", line 61
    except InvalidPage, e:
                      ^
SyntaxError: invalid syntax

**Comment by trawick** [comment]
Can't this be closed?  It seems that this particular issue was fixed via https://github.com/aldryn/aldryn-common/commit/2d07ab78385049bc016e93ada157002b0479f14a

**Comment by czpython** [comment]
@trawick I thought about it but I've not had time to verify if that commit is all that was needed for python 3 compatibility. So I've left this open more as a reminder for me to check..

**Comment by trawick** [comment]
@czpython I understand.

FWIW:

* I can't find (with 2to3) any issues in aldryn-search 0.2.10 for Python >= 3.2 (Python 3.1 is missing ``callable()``)
* it works for me so far with 3.4, but I might not be exercising much
* the issue was misfiled
* at least now nobody wonders if that try/except has been fixed :)

Meanwhile, 2to3 finds stuff to fix in aldryn-common 1.0.0, but that's another repo, with at least a ticket and pull request which are related.

Best wishes/thanks for your help/etc.

**Comment by DmytroLitvinov** [comment]
Hi @FinalAngel ,
I think we can close this issue

**Comment by FinalAngel** [comment]
thanks @DmytroLitvinov
